"""Elasticsearch index creation and bulk indexing.

Creates four indices:
  1. triage-file-metadata -- keyword/text fields for structured queries + regex-extracted entities
  2. triage-retrieval     -- semantic_text (auto-embedded via local e5 model)
  3. triage-sar-reports   -- SAR reports generated by the Elastic Workflow
  4. triage-quarantine    -- quarantined files that resisted extraction

Only format-based entities (email addresses, financial reference IDs) are extracted
via regex during ingestion. Person names, companies, and operations are NOT
pre-extracted -- the LLM in Agent Builder performs entity resolution at query time
by cross-referencing text content, email metadata, and financial identifiers.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from typing import Sequence

from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk
from rich.progress import Progress

from .config import (
    ELASTIC_INFERENCE_ENDPOINT_ID,
    ELASTIC_INFERENCE_MODEL,
    INDEX_FILE_METADATA,
    INDEX_QUARANTINE,
    INDEX_RETRIEVAL,
    INDEX_SAR_REPORTS,
    Config,
)
from .extractor import ExtractedFile

logger = logging.getLogger(__name__)

# --- Regex patterns for lightweight entity extraction ---

_RE_EMAIL = re.compile(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+")
_RE_FINANCIAL_REF = re.compile(
    r"(?:"
    r"(?:TXN|INV|REF)-[\w-]{4,}"  # transaction / invoice references
    r"|[A-Z]{2}\d{2}[A-Z0-9]{10,30}"  # IBAN-like patterns
    r"|bc1[a-zA-HJ-NP-Z0-9]{25,39}"  # bech32 Bitcoin addresses
    r"|[13][a-km-zA-HJ-NP-Z1-9]{25,34}"  # legacy Bitcoin addresses
    r")",
)

def _extract_entities(text: str) -> dict[str, list[str]]:
    """Extract format-based entities from text using regex.

    Only extracts entities with unambiguous structural patterns (email addresses,
    financial reference IDs). Person names, company names, and operation names are
    intentionally NOT extracted here -- the LLM in Agent Builder handles entity
    resolution at query time by cross-referencing text content across documents.
    """
    emails = list(set(_RE_EMAIL.findall(text)))
    financial_refs = list(set(_RE_FINANCIAL_REF.findall(text)))
    return {
        "entities_email": emails,
        "entities_financial_ref": financial_refs,
    }


def create_inference_endpoint(es: Elasticsearch, config: Config) -> None:
    """Create the inference endpoint using the locally-deployed e5 model."""
    try:
        es.inference.get(inference_id=ELASTIC_INFERENCE_ENDPOINT_ID)
        logger.info("Inference endpoint '%s' already exists", ELASTIC_INFERENCE_ENDPOINT_ID)
        return
    except Exception:
        pass

    body = {
        "service": "elasticsearch",
        "service_settings": {
            "model_id": ELASTIC_INFERENCE_MODEL,
            "num_allocations": 1,
            "num_threads": 1,
        },
    }

    try:
        es.options(request_timeout=300).inference.put(
            inference_id=ELASTIC_INFERENCE_ENDPOINT_ID,
            task_type="text_embedding",
            body=body,
        )
        logger.info("Created inference endpoint '%s' with model '%s'",
                     ELASTIC_INFERENCE_ENDPOINT_ID, ELASTIC_INFERENCE_MODEL)
    except Exception as exc:
        logger.error(
            "Could not create inference endpoint: %s", exc,
        )
        raise

    _wait_for_model_allocation(es)


def _wait_for_model_allocation(es: Elasticsearch, timeout: int = 300) -> None:
    """Block until the ML model is fully allocated (downloaded + deployed)."""
    import time
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            resp = es.ml.get_trained_models_stats(model_id=ELASTIC_INFERENCE_MODEL)
            models = resp.get("trained_model_stats", [])
            if models:
                deployment = models[0].get("deployment_stats", {})
                state = deployment.get("state", "")
                if state == "started":
                    alloc = deployment.get("allocation_status", {})
                    if alloc.get("state") == "fully_allocated":
                        logger.info("Model '%s' fully allocated", ELASTIC_INFERENCE_MODEL)
                        return
            logger.info("Waiting for model allocation... (state=%s)",
                       models[0].get("deployment_stats", {}).get("state", "unknown") if models else "no stats")
        except Exception as exc:
            logger.debug("Model stats check: %s", exc)
        time.sleep(10)
    logger.warning("Model allocation did not complete within %ds — ingestion may be slow initially", timeout)


def create_indices(es: Elasticsearch) -> None:
    """Create triage indices if they don't exist."""

    # 1. File metadata index (with entity keyword fields for structured queries)
    if not es.indices.exists(index=INDEX_FILE_METADATA):
        es.indices.create(
            index=INDEX_FILE_METADATA,
            body={
                "settings": {"number_of_replicas": 0},
                "mappings": {
                    "_meta": {
                        "description": "File metadata from a seized data source for forensic triage. "
                        "Contains file paths, types, sizes, extracted text, email metadata, "
                        "and regex-extracted entities (emails, financial refs). Person/company "
                        "identification is delegated to the LLM at query time."
                    },
                    "properties": {
                        "file_path": {"type": "keyword"},
                        "file_name": {"type": "keyword"},
                        "file_size": {"type": "long"},
                        "mime_type": {"type": "keyword"},
                        "file_extension": {"type": "keyword"},
                        "text_content": {"type": "text", "analyzer": "standard"},
                        "text_preview": {"type": "text"},
                        "element_types": {"type": "keyword"},
                        "is_image": {"type": "boolean"},
                        "is_encrypted": {"type": "boolean"},
                        "email_subject": {"type": "text", "fields": {"keyword": {"type": "keyword"}}},
                        "email_from": {"type": "keyword"},
                        "email_to": {"type": "keyword"},
                        "entities_financial_ref": {"type": "keyword"},
                        "entities_email": {"type": "keyword"},
                        "indexed_at": {"type": "date"},
                        "source_archive": {"type": "keyword"},
                        "source_archive_path": {"type": "keyword"},
                        "extraction_method": {"type": "keyword"},
                        "extraction_status": {"type": "keyword"},
                        "detected_mime": {"type": "keyword"},
                        "content_hash": {"type": "keyword"},
                        "language_detected": {"type": "keyword"},
                        "page_count": {"type": "integer"},
                        "duration_seconds": {"type": "float"},
                    },
                },
            },
        )
        logger.info("Created index '%s'", INDEX_FILE_METADATA)

    # 2. Retrieval index with semantic_text (auto-embedded by Elastic Inference Service)
    if not es.indices.exists(index=INDEX_RETRIEVAL):
        es.indices.create(
            index=INDEX_RETRIEVAL,
            body={
                "settings": {"number_of_replicas": 0},
                "mappings": {
                    "_meta": {
                        "description": "Full-text content from seized data source files with semantic "
                        "embeddings for conversational retrieval via Agent Builder."
                    },
                    "properties": {
                        "content": {
                            "type": "semantic_text",
                            "inference_id": ELASTIC_INFERENCE_ENDPOINT_ID,
                        },
                        "file_path": {"type": "keyword"},
                        "file_name": {"type": "keyword"},
                        "file_extension": {"type": "keyword"},
                        "mime_type": {"type": "keyword"},
                        "source_archive": {"type": "keyword"},
                        "extraction_method": {"type": "keyword"},
                    },
                },
            },
        )
        logger.info("Created index '%s'", INDEX_RETRIEVAL)

    # 3. SAR reports index (for workflow output)
    if not es.indices.exists(index=INDEX_SAR_REPORTS):
        es.indices.create(
            index=INDEX_SAR_REPORTS,
            body={
                "settings": {"number_of_replicas": 0},
                "mappings": {
                    "_meta": {
                        "description": "Suspicious Activity Reports generated by "
                        "the SAR Elastic Workflow. Each document is a FinCEN-aligned report "
                        "for a specific entity, produced from Elasticsearch queries."
                    },
                    "properties": {
                        "entity": {"type": "keyword"},
                        "generated_at": {"type": "date"},
                        "total_documents": {"type": "integer"},
                        "transaction_count": {"type": "integer"},
                        "communication_count": {"type": "integer"},
                        "financial_ref_count": {"type": "integer"},
                        "evidence_files": {"type": "text"},
                        "financial_documents": {"type": "text"},
                        "communications": {"type": "text"},
                        "financial_refs": {"type": "text"},
                        "workflow_version": {"type": "keyword"},
                    },
                },
            },
        )
        logger.info("Created index '%s'", INDEX_SAR_REPORTS)

    # 4. Quarantine index (for problem child tracking)
    if not es.indices.exists(index=INDEX_QUARANTINE):
        es.indices.create(
            index=INDEX_QUARANTINE,
            body={
                "settings": {"number_of_replicas": 0},
                "mappings": {
                    "_meta": {
                        "description": "Quarantined files that resisted all extraction methods. "
                        "Tracked here for visibility and LLM-assisted resolution."
                    },
                    "properties": {
                        "file_path": {"type": "keyword"},
                        "file_name": {"type": "keyword"},
                        "file_size": {"type": "long"},
                        "mime_type": {"type": "keyword"},
                        "magic_description": {"type": "text"},
                        "entropy": {"type": "float"},
                        "attempted_methods": {"type": "keyword"},
                        "error_messages": {"type": "text"},
                        "quarantined_at": {"type": "date"},
                        "status": {"type": "keyword"},
                        "llm_analysis": {"type": "text"},
                        "resolved_at": {"type": "date"},
                        "resolution_method": {"type": "keyword"},
                    },
                },
            },
        )
        logger.info("Created index '%s'", INDEX_QUARANTINE)


def delete_indices(es: Elasticsearch) -> None:
    """Delete all triage indices (for re-ingestion)."""
    for idx in [INDEX_FILE_METADATA, INDEX_RETRIEVAL, INDEX_SAR_REPORTS, INDEX_QUARANTINE]:
        if es.indices.exists(index=idx):
            es.indices.delete(index=idx)
            logger.info("Deleted index '%s'", idx)


def index_metadata(es: Elasticsearch, files: Sequence[ExtractedFile]) -> int:
    """Bulk-index file metadata with extracted entity keywords."""

    def _actions():
        for f in files:
            entities = _extract_entities(f.text_content)

            doc = {
                "_index": INDEX_FILE_METADATA,
                "_id": f.file_path,
                "file_path": f.file_path,
                "file_name": f.file_name,
                "file_size": f.file_size,
                "mime_type": f.mime_type,
                "file_extension": f.file_extension,
                "text_content": f.text_content[:10000],
                "text_preview": f.text_content[:500],
                "element_types": f.element_types,
                "is_image": f.is_image,
                "is_encrypted": f.is_encrypted,
                "indexed_at": datetime.now(timezone.utc).isoformat(),
                "extraction_method": f.extraction_method,
                "extraction_status": f.extraction_status,
                **{k: v for k, v in entities.items() if v},
            }

            if f.source_archive:
                doc["source_archive"] = f.source_archive
            if f.source_archive_path:
                doc["source_archive_path"] = f.source_archive_path
            if f.detected_mime:
                doc["detected_mime"] = f.detected_mime
            if f.content_hash:
                doc["content_hash"] = f.content_hash
            if f.language_detected:
                doc["language_detected"] = f.language_detected
            if f.page_count is not None:
                doc["page_count"] = f.page_count
            if f.duration_seconds is not None:
                doc["duration_seconds"] = f.duration_seconds

            if "email_subject" in f.metadata:
                doc["email_subject"] = f.metadata["email_subject"]
            if "email_from" in f.metadata:
                doc["email_from"] = f.metadata["email_from"]
                val = f.metadata["email_from"]
                if isinstance(val, list):
                    entities["entities_email"].extend(val)
                else:
                    entities["entities_email"].append(val)
            if "email_to" in f.metadata:
                doc["email_to"] = f.metadata["email_to"]
                val = f.metadata["email_to"]
                if isinstance(val, list):
                    entities["entities_email"].extend(val)
                else:
                    entities["entities_email"].append(val)

            if entities["entities_email"]:
                flat = [e for e in entities["entities_email"] if isinstance(e, str)]
                doc["entities_email"] = list(set(flat))

            yield doc

    success, errors = bulk(es, _actions(), raise_on_error=False, stats_only=False)
    if errors:
        logger.warning("Metadata indexing had %d errors", len(errors))
        for err in errors[:3]:
            logger.warning("Sample error: %s", err)
    logger.info("Indexed %d metadata documents", success)
    return success


def index_retrieval_content(es: Elasticsearch, files: Sequence[ExtractedFile]) -> int:
    """Bulk-index file content into the semantic_text retrieval index.

    Elasticsearch handles chunking and embedding generation automatically
    via the local e5 model. Each index call may take a few seconds while
    the model generates embeddings.
    """
    indexed = 0
    errors_count = 0
    es_slow = es.options(request_timeout=120)

    with Progress() as progress:
        task = progress.add_task("Indexing retrieval content...", total=len(files))
        for f in files:
            if not f.text_content.strip():
                progress.advance(task)
                continue
            try:
                doc = {
                    "content": f.text_content[:50000],
                    "file_path": f.file_path,
                    "file_name": f.file_name,
                    "file_extension": f.file_extension,
                    "mime_type": f.mime_type,
                }
                if f.source_archive:
                    doc["source_archive"] = f.source_archive
                if f.extraction_method:
                    doc["extraction_method"] = f.extraction_method

                es_slow.index(
                    index=INDEX_RETRIEVAL,
                    id=f.file_path,
                    document=doc,
                )
                indexed += 1
            except Exception as exc:
                logger.warning("Failed to index %s for retrieval: %s", f.file_path, exc)
                errors_count += 1
            progress.advance(task)

    logger.info("Indexed %d retrieval documents (%d errors)", indexed, errors_count)
    return indexed


def index_quarantine_records(
    es: Elasticsearch,
    records: Sequence,
) -> int:
    """Bulk-index quarantine records from the problem_child module."""

    def _actions():
        for r in records:
            doc = r.to_dict() if hasattr(r, "to_dict") else dict(r)
            doc["_index"] = INDEX_QUARANTINE
            doc["_id"] = doc.get("file_path", "")
            yield doc

    if not records:
        return 0

    success, errors = bulk(es, _actions(), raise_on_error=False, stats_only=False)
    if errors:
        logger.warning("Quarantine indexing had %d errors", len(errors))
    logger.info("Indexed %d quarantine records", success)
    return success
